/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.expt2.university.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.rm2pt.expt2.university.ide.contentassist.antlr.internal.InternalDslParser;
import org.rm2pt.expt2.university.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPersonAccess().getAlternatives(), "rule__Person__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getUniversityAccess().getGroup(), "rule__University__Group__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_4(), "rule__University__Group_4__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_4_3(), "rule__University__Group_4_3__0");
			builder.put(grammarAccess.getSchoolAccess().getGroup(), "rule__School__Group__0");
			builder.put(grammarAccess.getSchoolAccess().getGroup_4(), "rule__School__Group_4__0");
			builder.put(grammarAccess.getSchoolAccess().getGroup_5(), "rule__School__Group_5__0");
			builder.put(grammarAccess.getSchoolAccess().getGroup_5_3(), "rule__School__Group_5_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup(), "rule__Teacher__Group__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_4(), "rule__Teacher__Group_4__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_5(), "rule__Teacher__Group_5__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_5_3(), "rule__Teacher__Group_5_3__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_6(), "rule__Teacher__Group_6__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_6_3(), "rule__Teacher__Group_6_3__0");
			builder.put(grammarAccess.getStudentAccess().getGroup(), "rule__Student__Group__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_3(), "rule__Student__Group_3__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_9(), "rule__Student__Group_9__0");
			builder.put(grammarAccess.getUniversityAccess().getNameAssignment_2(), "rule__University__NameAssignment_2");
			builder.put(grammarAccess.getUniversityAccess().getContainAssignment_4_2(), "rule__University__ContainAssignment_4_2");
			builder.put(grammarAccess.getUniversityAccess().getContainAssignment_4_3_1(), "rule__University__ContainAssignment_4_3_1");
			builder.put(grammarAccess.getSchoolAccess().getNameAssignment_2(), "rule__School__NameAssignment_2");
			builder.put(grammarAccess.getSchoolAccess().getSidAssignment_4_1(), "rule__School__SidAssignment_4_1");
			builder.put(grammarAccess.getSchoolAccess().getContainPersonAssignment_5_2(), "rule__School__ContainPersonAssignment_5_2");
			builder.put(grammarAccess.getSchoolAccess().getContainPersonAssignment_5_3_1(), "rule__School__ContainPersonAssignment_5_3_1");
			builder.put(grammarAccess.getTeacherAccess().getNameAssignment_2(), "rule__Teacher__NameAssignment_2");
			builder.put(grammarAccess.getTeacherAccess().getIdAssignment_4_1(), "rule__Teacher__IdAssignment_4_1");
			builder.put(grammarAccess.getTeacherAccess().getWorkInAssignment_5_2(), "rule__Teacher__WorkInAssignment_5_2");
			builder.put(grammarAccess.getTeacherAccess().getWorkInAssignment_5_3_1(), "rule__Teacher__WorkInAssignment_5_3_1");
			builder.put(grammarAccess.getTeacherAccess().getTeachAssignment_6_2(), "rule__Teacher__TeachAssignment_6_2");
			builder.put(grammarAccess.getTeacherAccess().getTeachAssignment_6_3_1(), "rule__Teacher__TeachAssignment_6_3_1");
			builder.put(grammarAccess.getStudentAccess().getNameAssignment_1(), "rule__Student__NameAssignment_1");
			builder.put(grammarAccess.getStudentAccess().getIdAssignment_3_1(), "rule__Student__IdAssignment_3_1");
			builder.put(grammarAccess.getStudentAccess().getStudyInAssignment_5(), "rule__Student__StudyInAssignment_5");
			builder.put(grammarAccess.getStudentAccess().getFollowAssignment_8(), "rule__Student__FollowAssignment_8");
			builder.put(grammarAccess.getStudentAccess().getFollowAssignment_9_1(), "rule__Student__FollowAssignment_9_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
