/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.expt2.university;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
