/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.expt2.university.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
